### ISSUE TITLE
neprivet.ru does not support https://. Please add Let's encrypt.

### ISSUE THREAD

**Issue by socketpair** [kryzhovnik/neprivet#5]

**Comment by kryzhovnik** [comment]
I see no reasons to do it, so far. It's just a single page!

There are reasons to keep avoiding https for this particular site:
- http is slightly faster then https (latency)
- additional complexity. 

Please, provide a meaningful reason to do what you've proposed, convince me.

**Comment by socketpair** [comment]
Modern browsers show red warning about insecure page. That's annoying.

**Comment by kryzhovnik** [comment]
Really?! What browser shows the warning for this site?

I've only known that browsers show warnings for non-https sites with secure forms.

**Comment by TemaSM** [comment]
Agree with @socketpair.
https://www.exabytes.digital/blog/red-not-secure-warning-for-http-websites-google-chrome
https://www.blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/

One additional advantage of using HTTPS, is that website may be served via http/2 (supports multiplexing out of the box) which actually significantly improves website loading time, and even (if we speak about optimizations and latency) wastes less mAh"s of visitor's smartphone/laptop battery, because of less required job to initiate connection and make http(s) requests:
https://istlsfastyet.com/

In my opinion, website even may be hosted as GitHub Pages, why not? 😃 
That will be the best option for you and visitors. More info here:
https://help.github.com/en/articles/securing-your-github-pages-site-with-https

**Comment by kryzhovnik** [comment]
@TemaSM thank you for the advice. I think you're right, going to move to Github Pages.

**Comment by neoromantique** [comment]
+1 
Came here to say that.

It also breaks some browsers with https-only extensions, there's no reason not to have https in 2020.

**Comment by rakshazi** [comment]
hello from 2020.
github pages supports auto-tls now. So you can just enforce https in your repo settings (pages section)

**Comment by kryzhovnik** [comment]
Okay, you guys got me. Just have moved the site to the Github pages. HTTPS is working now.

**Comment by 1dNDN** [comment]
Update the links on the site so that they lead to https, not http, as they are now

**Comment by kryzhovnik** [comment]
> Update the links on the site so that they lead to https, not http, as they are now

Fixed. Thanks for reminding
